services:
  server:
    container_name: mems-back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      mems-network:
        ipv4_address: 192.168.1.3
    ports:
      - "8080:8080"
    stdin_open: true 
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  mems-network:
    external: true
